
services:
  nginx:
    image: nginx:latest # Original image
    container_name: nginx
    ports:
      - 80:80 # Map port 80 on the host to port 80 on the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the local nginx.conf file to the container
    depends_on:
      - hello # Wait for the hello service to be ready before starting the nginx service
  hello:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: hello
    expose:
      - 8080 # Expose port 8080 on the container, allowing other services to access it